final project/adoption_cat_site/adoption_cat_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('cats/', include('adoptions.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

final project/adoption_cat_site/adoptions/urls.py
from . import views
from django.urls import path

app_name= 'adoptions'
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:cat_id>/', views.detail, name='detail' ),
    path('contact/', views.contact, name='contact'),
    path('recently-adopted/', views.recently_adopted, name='recently-adopted'),
    path('<int:cat_id>/adopt-cat/', views.adopt_cat, name='adopt-cat'),
]

final project/adoption_cat_site/users/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("", include('django.contrib.auth.urls')),
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
]

final project/adoption_cat_site/adoptions/models.py
from django.db import models
import datetime
from django.utils import timezone
import random
import string
from users.forms import User

def rename_upload_photo(instance, filename):
    filename_splited = filename.split(".")
    photo_extension = filename_splited[1]
    new_filename = ""
    for letter in filename_splited[0]:
        new_filename += random.choice(string.ascii_letters)
    return "adoptions/" + new_filename + "." + photo_extension

class Cat(models.Model):
    cat_name_text = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published')
    adoption_date = models.DateTimeField('date adopted', default=timezone.now())
    adopted = models.BooleanField(default=False)
    human = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.cat_name_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    

class Cat_Details(models.Model):

    details = models.ForeignKey(Cat, on_delete=models.CASCADE)
    description_text = models.CharField(max_length=200)
    age = models.IntegerField(default=0)
    location = models.CharField(max_length=200)
    cat_photo = models.ImageField(upload_to=rename_upload_photo, default='static/adoptions/cat_static.jpg')

    def __str__(self):
        return self.description_text

final project/adoption_cat_site/adoptions/forms.py
from django import forms

class CatAdoptionForm(forms.Form):
    CHOICES = [("1", "Yes"), ("2", "No")]
    want_the_cat = forms.ChoiceField(label="Do you want to adopt this cat?",
                                     widget=forms.RadioSelect,
                                     choices=CHOICES)
    had_a_cat = forms.ChoiceField(label="Have you adopted a cat in the past?",
                                  widget=forms.RadioSelect,
                                  choices=CHOICES)
    keep_in_contact = forms.ChoiceField(label="Do you want to keep in contact with the person who is currently fostering the cat?",
                                        widget=forms.RadioSelect,
                                        choices=CHOICES)
    other_mentions = forms.CharField(label="Other mentions")

final project/adoption_cat_site/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2", "first_name", "last_name"]

final project/adoption_cat_site/adoptions/views.py
from django.shortcuts import render, redirect
from .models import Cat, Cat_Details
from .forms import CatAdoptionForm
from django.utils import timezone
from users import views

class CatWithPhoto:
    def __init__(self, cat_object, cat_image):
        self.cat_obj = cat_object
        self.cat_img = cat_image

def index(request):
    latest_cat_list = []
    cat_list = Cat.objects.filter(adopted=False).order_by('pub_date')
    for cat in cat_list:
        cat_details = Cat_Details.objects.get(details=cat.pk)
        latest_cat_list.append(CatWithPhoto(cat, cat_details.cat_photo))

    adopted_cat_list = []
    adopted_cats = Cat.objects.filter(adopted=True).order_by('-adoption_date')
    for cat in adopted_cats:
        cat_details = Cat_Details.objects.get(details=cat.pk)
        adopted_cat_list.append(CatWithPhoto(cat, cat_details.cat_photo))
        if len(adopted_cat_list) == 3:
            break

    context = {
        'latest_cat_list': latest_cat_list,
        'adopted_cat_list': adopted_cat_list,
    }
    return render(request,'adoptions/index.html', context)

def detail(request, cat_id):
    cat = Cat.objects.get(pk=cat_id)
    cat_details = Cat_Details.objects.get(details=cat.pk)
    return render(request, 'adoptions/detail.html', {'cat':cat, 'cat_details':cat_details})

def contact(request):
    return render(request, 'adoptions/contact.html')

def recently_adopted(request):
    adopted_cat_list = []
    adopted_cats = Cat.objects.filter(adopted=True).order_by('-adoption_date')
    for cat in adopted_cats:
        cat_details = Cat_Details.objects.get(details=cat.pk)
        adopted_cat_list.append(CatWithPhoto(cat, cat_details.cat_photo))
    return render(request,'adoptions/recently_adopted.html', {'adopted_cat_list': adopted_cat_list})


def adopt_cat(request, cat_id):
    if not request.user.is_authenticated:
        return redirect('/accounts/login')

    form = CatAdoptionForm()
    cat = Cat.objects.get(pk=cat_id)
    cat_details = Cat_Details.objects.get(details=cat.pk)
    if request.method == "POST":
        print(request.POST["want_the_cat"])
        print(request.POST["had_a_cat"])
        print(request.POST["keep_in_contact"])
        print(request.POST["other_mentions"])
        want_the_cat = request.POST["want_the_cat"]
        if str(want_the_cat) != "1":
            print("Do not want the cat?")
            return render(request, 'adoptions/not_adopted.html')


        cat.adopted = True
        cat.adoption_date = timezone.now()
        cat.human = request.user
        cat.save()

        return redirect('/cats')

    return render(request, 'adoptions/adopt_cat.html', {'cat':cat, 'cat_details':cat_details, 'form':form})

final project/adoption_cat_site/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from adoptions.models import Cat

def signup(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()

        return redirect("/cats")
    else:
        form = RegisterForm()

    return render(response, "registration/signup.html", {"form":form})


def profile(response):
    if response.user.is_authenticated:
        cats = Cat.objects.filter(human=response.user)
        return render(response, "users/profile.html", {'cats':cats})
    else:
        return redirect('/accounts/login')

final project/adoption_cat_site/adoptions/templates/adoptions/adopt_cat.html
<!doctype html>
{% load static %}
<html>

{% include "adoptions/base.html" %}
{% block content %}
<style>
    h1 {
        margin-left: 5%;
        margin-right: 5%;
        color: black;
        text-shadow: 3px 3px 5px #0000006e;
        font-family: "Lucida Console", monospace;
        align-content: center;
        font-size: 4vw;
        border-left: 7px solid green;
        background-color: lightgrey;
        padding-top: 1%;
        padding-right: 1%;
        padding-bottom: 1%;
        padding-left: 1%;
    }
    .date_published{
        color: grey;
        font-size: 75%;
    }
   .adopt_form {
        padding: 5%;
    }
    .submit {
        margin-top: -9%;
        padding: 5%;
    }
</style>
<body>
<h1>Adoption form</h1>
<div class="container">
  <form action="/cats/{{ cat.id }}/adopt-cat/" method="post">
      {% csrf_token %}
      <div class="adopt_form">
        <p><strong>{{form.want_the_cat.label }}</strong></p>
        <p> {{ form.want_the_cat }}</p>
        <p><strong>{{form.had_a_cat.label }}</strong></p>
        <p> {{ form.had_a_cat }}</p>
        <p><strong>{{form.keep_in_contact.label }}</strong></p>
        <p> {{ form.keep_in_contact }}</p>
        <p><strong>{{form.other_mentions.label }}</strong></p>
        <p> {{ form.other_mentions }}</p>
      </div>
       <div class="submit">
          <input type="submit" value="Adopt">
          <br><br>
      </div>
  </form>
{% endblock %}
</div>
</body>
{% include "adoptions/footer.html" %}
</html>

final project/adoption_cat_site/adoptions/templates/adoptions/adopted_carousel.html
<!DOCTYPE html>
<html lang="en">
<body>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        {% if adopted_cat_list %}
        {% for cat in adopted_cat_list %}
        <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter }}" {% if forloop.counter == 1 %} class="active"{% endif %}></li>
        {% endfor %}
        {% endif %}
    </ol>
    <div class="carousel-inner">
    {% if adopted_cat_list %}
    {% for cat in adopted_cat_list %}
        <div class="carousel-item{% if forloop.counter == 1 %} active{% endif %}">
            <img class="d-block w-100" src="{{ cat.cat_img.url }}" alt="First slide">
            <h5>{{ cat.cat_obj.cat_name_text }}</h5>
        </div>
    {% endfor %}
    {% endif %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
    </a>
</div>
</body>
</html>

final project/adoption_cat_site/adoptions/templates/adoptions/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Cat adoption site</title>
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;

        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      img {
      width: auto;
      height: 300px;
      object-fit: cover;
      }
      .home-page{
      margin: 10%;
      }
      .spacing {
        margin: 2%;
      }
      .logo_site{
        width: 40px;
        height: 40px;
      }
      .menu-items {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
      }
      .welcome {
      color: grey;
      text-align:justify;
      margin-top:2%;
      margin-right: -35%;
      margin-bottom: -2%;
      font-family: Helvetica;
      }
      a:link {
      text-decoration: none;
      }
      a:visited {
      text-decoration: none;
      }
    </style>
  </head>
  <body>
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About us</h4>
          <p class="text-muted">We are a site that promotes and supports cat adoption.<br>
            <br>There are a lot of stray cats in this world that need love and a home (also food).
            <br>Please check our page, so you can choose your new friend (or friends, maybe).
            <br><br><strong>ADOPT! DON'T SHOP!</strong></p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="{% url 'adoptions:contact' %}" class="text-white">Contact details</a></li>
            <li><a href="https://www.facebook.com/profile.php?id=100078511217106" class="text-white">Like us on Facebook</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">

    <div class="container">
      <div class="menu-items">
        <a href="{% url 'adoptions:index' %}" class="navbar-brand d-flex align-items-center">
          <img class="logo_site" src="{% static 'adoptions/cat_logo_no_background.png' %}"/>
          <strong>Home</strong>
        </a>
         <a href="{% url 'adoptions:recently-adopted' %}" class="navbar-brand d-flex align-items-center">
         <strong>Adopted cats</strong>
         </a>
        {% if request.user.is_authenticated %}
          <a href="{% url 'logout' %}" class="navbar-brand d-flex align-items-center">
          <strong>Logout</strong>
          </a>
          <a href="{% url 'profile' %}" class="navbar-brand d-flex align-items-center">
          <strong>Profile</strong>
          </a>
        {% else %}
         <a href="{% url 'login' %}" class="navbar-brand d-flex align-items-center">
         <strong>Login</strong>
         </a>
         <a href="{% url 'signup' %}" class="navbar-brand d-flex align-items-center">
         <strong>Signup</strong>
         </a>
        {% endif %}
      </div>
      {% if request.user.is_authenticated %}
        <div class="welcome">
          <a href="{% url 'profile' %}" class="welcome"><p><strong>Welcome {{ user.first_name }} {{ user.last_name }}!</strong></p></a>
        </div>
      {% endif %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>
<main>
  <div class="spacing">
  </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

final project/adoption_cat_site/adoptions/templates/adoptions/contact.html
<!doctype html>
{% load static %}
<html>
{% include "adoptions/base.html" %}
<style>
    .flex-box {
      display: flex;
    }
    h1 {
    margin-left: 5%;
    margin-right: 5%;
    color: black;
    text-shadow: 3px 3px 5px #0000006e;
    font-family: "Lucida Console", monospace;
    align-content: center;
    font-size: 4vw;
    border-left: 7px solid green;
    background-color: lightgrey;
    padding-top: 1%;
    padding-right: 1%;
    padding-bottom: 1%;
    padding-left: 1%;
    }
    .text_area {
    padding: 1%;
    margin: 5%;
    width: 40%;
    height: 50%;
    border: 1px solid green;
    box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);;
    text-shadow: black;
    box-sizing: border-box;
    }
    .maps {
    margin: 5%;
    width: 45%;
    height: 50%;
    }
    .image-adopt{
    display: inline-block;
    }
    .logo_cat_site {
      margin-left: 78%;
      width: 25%;
      height: 25%;
    }
</style>
<body>
    <h1>Contact Details</h1>
    <div class="flex-box">
      <div class="text_area">
          <div class="text">
            <p><b>Address: </b></p><p>VIVO! Cluj-Napoca, Strada Avram Iancu 492-500, Florești</p>
            <p><b>Phone: </b></p><p>+40745123123</p>
            <p><b>E-mail: </b></p><p>catadoptioncluj@gmail.com</p>
            <img class="logo_cat_site" src="{% static 'adoptions/cat_logo_no_background.png' %}"/>
          </div>
      </div>
      <div class="image-adopt">
        <img class="logo" src="{% static 'adoptions/logo_adopt_cat.png' %}"/>
      </div>
    </div>
<div class="maps">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7974.825692084461!2d23.525565894868734!3d46.7527554458846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47490e47689260ed%3A0x941b29241ee14710!2sVIVO*21%20Cluj-Napoca!5e0!3m2!1sro!2sro!4v1644093089148!5m2!1sro!2sro" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
  </body>
{% include "adoptions/footer.html" %}
</html>

final project/adoption_cat_site/adoptions/templates/adoptions/detail.html
<!doctype html>
<html>
{% load static %}
{% include "adoptions/base.html" %}
  <style>
    body {
      background-size: 100% 100%;
      background: rgb(78,78,78);
      background-color: whitesmoke;
    }
    img {
      width: 25%;
      height: 25%;
      margin: 3%;
      box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
    }
    .flex-box {
      display: flex;
    }
    .details {
      flex: 1;
    }
    h1 {
    color: black;
    margin-right: 5%;
    text-shadow: 3px 3px 5px #0000006e;
    font-family: "Lucida Console", monospace;
    align-content: center;
    font-size: 4vw;
    border-left: 7px solid green;
    background-color: lightgrey;
    padding-top: 1%;
    padding-right: 1%;
    padding-bottom: 1%;
    padding-left: 1%;
    }

    .button {
    border: transparent;
    text-decoration: solid;
    display: inline-block;
    background-color: transparent;
    font-size: medium;
    cursor: pointer;
    }
    .confirm {
      height: 20%;
      width: 55%;
      margin-top: 5%;
    }

    .adopt {background-color: #4CAF50;color: white;font-family: Arial, sans-serif;font-size: medium; text-decoration: none;}
    .adopt {box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);}
    .adopt {border-color: transparent;}
    .adopt {padding: 5% 30%;}
    .adopt {transition-duration: 0.4s;}
    .adopt:hover {
    background-color: #4CAF50; /* Green */
    color: white;
    font-size: x-large;
    }

    .text_area {
      width: 95%;
      height: 50%;
      border: 1px solid green;
      box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);;
      text-shadow: black;
      box-sizing: border-box;
    }
    .text {
      color:black;
      font-size: 110%;
      margin-left: 2%;
      margin-top: 2%;
      margin-bottom: 2%;
      margin-right: 2%;
    }
  </style>

  <body>
    <div class="flex-box">
      <img class="details" src="{{ cat_details.cat_photo.url }}" type="jpg"/>
      <div class="details">
        <title>{{ cat.cat_name_text }}</title>
        <h1>{{ cat.cat_name_text }}</h1>
        <div class="text_area">
          <div class="text">
            <p><b>Description</b></p>
            <p>{{ cat_details.description_text }}</p>
            <p>Age: {{ cat_details.age }}</p>
            <p>Location: {{ cat_details.location }}</p>
          </div>
        </div>
        <div class="confirm">
          <a href="/cats/{{ cat.id }}/adopt-cat" class=".button adopt" name="adopt"><b>Adopt me</b></a>
        </div>
      </div>
    </div>
  </body>
{% include "adoptions/footer.html" %}
</html>

final project/adoption_cat_site/adoptions/templates/adoptions/footer.html
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Adoption cat site</p>
    <p class="mb-0">Site designed by Sonia Stefania Pop - 2022</a>.</p>
    <p class="mb-0">All photos are taken by Sonia Stefania Pop</a>.</p>
  </div>
</footer>

final project/adoption_cat_site/adoptions/templates/adoptions/index.html
<!doctype html>
{% load static %}
<html lang="en">
{% include "adoptions/base.html" %}
<style>
  .date_published{
    color: grey;
    font-size: 75%;
  }
</style>
<body>
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Recently Adopted Cats</h1>
        <p class="lead text-muted">Check the recently adopted cats</p>
        {% include "adoptions/adopted_carousel.html" %}
        <p>
          <a href="{% url 'adoptions:recently-adopted' %}" class="btn btn-success my-2">Adopted cats</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% if latest_cat_list %}
          {% for cat in latest_cat_list %}
            <div class="col">
              <div class="card shadow-sm">
                <img class="details" src="{{ cat.cat_img.url }}" type="jpg"/>
                <div class="card-body">
                  <p class="card-text"><b>{{ cat.cat_obj.cat_name_text }}</b></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a href="/cats/{{ cat.cat_obj.id }}/" class="btn btn-sm btn-outline-secondary">View</a>
                    </div>
                    <p class="date_published"><b>{{ cat.cat_obj.pub_date }}</b></p>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>

</main>

{% include "adoptions/footer.html" %}

  </body>
</html>

final project/adoption_cat_site/adoptions/templates/adoptions/not_adopted.html
<!doctype html>
{% load static %}
<html>
{% include "adoptions/base.html" %}
{% block content %}
<style>
    h1 {
        margin-left: 5%;
        margin-right: 5%;
        color: black;
        text-shadow: 3px 3px 5px #0000006e;
        font-family: "Lucida Console", monospace;
        align-content: center;
        font-size: 4vw;
        border-left: 7px solid green;
        background-color: lightgrey;
        padding-top: 1%;
        padding-right: 1%;
        padding-bottom: 1%;
        padding-left: 1%;
    }

   .thanks_text {
        margin-left: 5%;
        padding-left: 1%;
    }
</style>
<body>
<h1>Adoption form</h1>
<div class="thanks_text">
    <p><strong>Thank you for your response! Hopefully you will want to adopt a cat soon. </strong></p>
</div>
<br><br><br>
{% endblock %}
</div>
</body>
{% include "adoptions/footer.html" %}
</html>

final project/adoption_cat_site/adoptions/templates/adoptions/recently_adopted.html
<!doctype html>
{% load static %}
<html lang="en">
{% include "adoptions/base.html" %}
<style>
  .date_published{
    color: grey;
    font-size: 75%;
  }
    h1 {
    margin-left: 5%;
    margin-right: 5%;
    color: black;
    text-shadow: 3px 3px 5px #0000006e;
    font-family: "Lucida Console", monospace;
    align-content: center;
    font-size: 4vw;
    border-left: 7px solid green;
    background-color: lightgrey;
    padding-top: 1%;
    padding-right: 1%;
    padding-bottom: 1%;
    padding-left: 1%;
    }
</style>
<body>
<h1>Adopted cats</h1>
<main>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% if adopted_cat_list %}
          {% for cat in adopted_cat_list %}
            <div class="col">
              <div class="card shadow-sm">
                <img class="details" src="{{ cat.cat_img.url }}" type="jpg"/>
                <div class="card-body">
                  <p class="card-text"><b>{{ cat.cat_obj.cat_name_text }}</b></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="text_area">
                      <p>Adoption date:</p><p class="date_published">{{ cat.cat_obj.adoption_date }}</p>
                  </div>
                    </div>

                </div>
              </div>
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
</main>
{% include "adoptions/footer.html" %}
</body>
</html>

final project/adoption_cat_site/users/templates/users/profile.html
<!doctype html>
{% load static %}
<html lang="en">
{% include "adoptions/base.html" %}
<style>
    .flex-box {
      display: flex;
    }
    h1 {
    margin-left: 5%;
    margin-right: 5%;
    color: black;
    text-shadow: 3px 3px 5px #0000006e;
    font-family: "Lucida Console", monospace;
    align-content: center;
    font-size: 4vw;
    border-left: 7px solid green;
    background-color: lightgrey;
    padding-top: 1%;
    padding-right: 1%;
    padding-bottom: 1%;
    padding-left: 1%;
    }
    .logo_cat_site {
      margin-left: 78%;
      width: 25%;
      height: 25%;
    }
    .text_area {
        padding: 1%;
        margin: 5%;
        width: 40%;
        height: 50%;
        border: 1px solid green;
        box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);;
        text-shadow: black;
        box-sizing: border-box;
    }
    .adopted-cats {
        padding: 1%;
        margin: 5%;
        width: 40%;
        height: 50%;
        border: 1px solid green;
        box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);;
        text-shadow: black;
        box-sizing: border-box;
    }
</style>
<body>
<h1>Profile</h1>
    <div class="flex-box">
      <div class="text_area">
          <div class="text">
            <p><b>First name: </b></p><p>{{ user.last_name }}</p>
            <p><b>Last name: </b></p><p>{{ user.first_name }} </p>
            <p><b>Username: </b></p><p>{{ user.username }}</p>
            <p><b>E-mail: </b></p><p>{{ user.email }}</p>
            <img class="logo_cat_site" src="{% static 'adoptions/cat_logo_no_background.png' %}"/>
          </div>
      </div>
      <div class="image-adopt">
        <img class="logo" src="{% static 'adoptions/logo_adopt_cat.png' %}"/>
      </div>
    </div>
    <div class="flex-box">
        <div class="adopted-cats">
            <p><strong>Adopted cats by you: </strong></p>
            <div class="cats">
                {% for cat in cats %}
                    <li>{{ cat.cat_name_text }}</li>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
{% include "adoptions/footer.html" %}
</html>